language: ruby
rvm:
- 2.3.1
install:
- bundle install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: _site
  target_branch: master
  on:
    branch: source
notifications:
  slack:
    secure: JfVg2wYlWLYxR2EEw5wbuexbflUgPY7y8RvvQPF8FZ0Od05RdUu4levBNde77xQOVz1CogWYThJREo5rKOmmp0GOTSjsdHu4C+fW2iKPSsGPHhWnAUuQDuq+9UMKWjpRN9x8sJBGoDsfV3lKozd/ciBIlqi49I8FHH7AID+1Lfd1KJt2Q7fDJhLivEAJCAZe4VZpuZzZgA1YUYmEMop3f2g5IzrMAm9+1hv5/xliCzs/sxBg0BEMzafaQIU5o80GfZNTlxwidT5VXwlteOH7t0PBJZx6fhkXOSIFD3RVsxIK3sRlCTZozq8bp1WdHx0uxkAkiKTVWVGjge+NK0fq5OTHROVFagV968khmtAfvCWOcD+v9xDthMG2TNQJQRny2PtMitfJKDOrpIbDk6f5tHwxBI43BAL7isIjiByJn8L0WaG3yibP6xg/5sLXKfanvz+HbfvxuuQYLpYwL1/DQ2Z9nsZT11GNPrA1N2LvWo11BpPSxsTQuvtXp8fTWWMxnu1vJMWM36mL66LG1XBr3/rCSbPDnu8ct3GMH9/Y8OIeJRieVEEfdvTTPRHDPa9lqiNxWaZ9mV1S53CuHgDDApgL6t30UxDIZuP7xGsTcqbbFSlwYLJNPtCdflkbcEcxMifAtzC6WyOGLT3tnXmAwOME7MnPYnrt0pCqixWd1Q8=
    on_success: change
    on_failure: always
    on_pull_requests: false
