
title: Your blog title
email: christopherjbischoff@gmail.com


permalink: /blog/:title

url: https://cjbischoff.github.io


# My variables
name: /home/cjbischoff
description: developer. curious. learner
google_verification: null

# File management
include: [".htaccess"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  # input: GFM
  hard_wrap: false
highlighter: rouge

# Any plugins within jekyll_plugin group from Gemfile
plugins:
  - jekyll-feed

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
