
title: Christopher J. Bischoff
email: christopherjbischoff@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cjbischoff@github.io"
twitter_username: cjbischoff
github_username: cjbischoff


permalink: /blog/:title



# My variables
name: /home/cjbischoff
description: developer. curious. learner
google_verification: null


sass:
  style: :compressed
  sass_dir: _sass

# File management
include: [".htaccess"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
    input: GFM
    auto_ids: true
    hard_wrap: false
    syntax_highlighter_opts:
      disable: true
highlighter: rouge

# Any plugins within jekyll_plugin group from Gemfile
plugins:
  - jekyll-feed

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
